### ISSUE TITLE
Do you mind readding wine? Got it fixed with a trick 

### ISSUE THREAD

**Issue by xhebox** [lluixhi/musl-extras#11]
I've submitted a patch though it may not be accepted. https://bugs.winehq.org/show_bug.cgi?id=41703

With this patch and other patches from alpine and gentoo, you should get wine worked well. I'm doing a musl-based distro but haven't updated this patch to my ports. I'll update it later so you can learn how i build it.

**Comment by xhebox** [comment]
If you're not interested in it, at least tell it to more people! I'm not fimilar with communities...

**Comment by xhebox** [comment]
a better workaround patch is out: https://bugs.winehq.org/show_bug.cgi?id=41703

**Comment by lluixhi** [comment]
Sorry I never got around to doing this, I'll add wine with the new patch.

**Comment by xhebox** [comment]
no matter, wine is a bastard :p
