### ISSUE TITLE
Mesa build problem

### ISSUE THREAD

**Issue by Cogitri** [lluixhi/musl-extras#13]
Hello,
Mesa doesn't build with VIDEO_CARDS="radeon radeonsi", but does build without those. Tried with both gcc 4.9.4 and 6.3.0. Can't seem to attach logs with github on my mobile, what'd be the best way to share them?

**Comment by Cogitri** [comment]
Okay, seems like Alpine Linux already fixed it. Gotta report back later

**Comment by lluixhi** [comment]
You could just post the compilation error at the end of the build log.

Is it the `<sys/stat.h>` patch that alpine is carrying?

I know for a fact that mesa with the `vulkan` use flag is broken in mesa right now with musl, but I haven't tried fixing it yet.

**Comment by Cogitri** [comment]
Kinda hard to cut those out on a mobile. The fix was the following

+    #hack to fix ENDIAN_CPU issue
+    _annoying_header="${_builddir}/src/amd/addrlib/inc/chip/r800/si_gb_reg.h"
+    echo -e "#define LITTLEENDIAN_CPU 1\n$(cat $_annoying_header)" > $_annoying_header

Found it here: https://patchwork.alpinelinux.org/patch/2556/

**Comment by lluixhi** [comment]
Could you pull the repo and try now? I think Alpine was overcomplicating it instead of patching the correct header. `u_endian.h`

**Comment by lluixhi** [comment]
vulkan appears to be building now at least

**Comment by Cogitri** [comment]
Builds fine now, thanks :)

**Comment by lluixhi** [comment]
I think I'm going to move these into the official musl repository now that we have a patch everyone actually needs :P
