### ISSUE TITLE
icecat build fails

### ISSUE THREAD

**Issue by Uramekus** [lluixhi/musl-extras#14]
it seems to miss a directory
/var/tmp/portage/www-client/icecat-52.0.2/work/icecat-52.0.2/browser/branding/unofficial/ does not exist

http://dpaste.com/1JAB4GE

**Comment by lluixhi** [comment]
Odd, I just built the most recent version without any issues.

Wait, why is the path "branding/unofficial" being used?
Do you have USE="bindist" enabled?

**Comment by Uramekus** [comment]
oh, USE="bindist mmx sse sse2" comes by default on musl stage3 so i didnt even realized it was there.

Sorry.
