### ISSUE TITLE
move stuff over to the official musl overlay

### ISSUE THREAD

**Issue by blueness** [lluixhi/musl-extras#5]
Okay people have been bugging me to move this stuff over to the official musl overlay at git://git.gentoo.org/proj/musl.git.  This makes sense so we have on consolidated repository.  I can give you commit access.

**Comment by blueness** [comment]
ping if you're not interested in this, just close this bug

**Comment by lluixhi** [comment]
@blueness 
Sorry I didn't respond -- I do want to move the packages in here over to the official musl overlay.

**Comment by blueness** [comment]
@lluixhi since its hosted on the gentoo site, I'll need your public ssh key.  Also, I recommend a .git config file like the following so that  you push simultaneously to the github mirror and the gentoo mirror.  Its important to keep both in sync.

```
[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
[remote "origin"]
    url = git+ssh://git@git.gentoo.org/proj/musl.git
    fetch = +refs/heads/*:refs/remotes/origin/*
    pushurl = git@github.com:gentoo/musl.git
    pushurl = git+ssh://git@git.gentoo.org/proj/musl.git
[remote "github"]
    url = git@github.com:gentoo/musl.git
    fetch = +refs/heads/*:refs/remotes/github/*
    fetch = +refs/pull/*/head:refs/remotes/github/pr/*
[branch "master"]
    remote = origin
    merge = refs/heads/master
```

**Comment by lluixhi** [comment]
I emailed you a while ago -- did you get it?

**Comment by blueness** [comment]
no!  i don't know what happened.  please send again.

**Comment by blueness** [comment]
i still got nothing, did you send to blueness@gentoo.org

**Comment by lluixhi** [comment]
still?

**Comment by blueness** [comment]
i just added you.  didn't you get my email confirming?

**Comment by lluixhi** [comment]
Got it. Thanks!
I'll start moving things over.
