### ISSUE TITLE
backport for gcc-4.9.x

### ISSUE THREAD

**Issue by stefson** [lluixhi/musl-extras#6]
hey there, 

I wonder if you could manage to backport two pullrequest for gcc 4.9.x? They are supposed to solve a bug which prevents the build of www-client/firefox [debug] on x86 [1], and fix a regression on amd64 [2] caused by [1]. They both may need a little adjustment, which I can't do on my own because I do lack a propper understanding of what those pullrequests are changing. 

1 = https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68470 
2 = https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68721 

thanks! :)

**Comment by lluixhi** [comment]
So first of all, this doesn't really belong on this repo, because I'm doing musl patches.

But anyway, the patch in [1] applies pretty cleanly to gcc-4.9.4:
http://pastebin.com/FWfT6ecv

And as far as I can tell, bug [2] is only relevant to GCC-6.1.0 -- the test case they provide does not seem to trigger an error with GCC-4.9.4

**Comment by stefson** [comment]
Well, I triggered the bug in [1] while building firefox with debug useflag on a musl profile. Therefore it seemed reasonable to ask for a little bit of help with it here? :) It might be triggered on a glibc system as well, but I have none at hand to test. 

it is line #1207 which I am uncertain about, in recent trunk it is 
       tree retval = NULL, real_retval = NULL, retbnd = NULL; 

while in gcc-4.9.3 and .4 as well it is 
       tree retval = NULL, real_retval = NULL; 

Is it safe to adjust/rebase this line?

**Comment by lluixhi** [comment]
Are you talking about the patch from [1]?

I applied it to 4.9.4 and linked the modified patch in the pastebin :P

That line is safe to change, because `split_function` in gcc-4.9.4 doesn't use a `retbnd` variable.

**Comment by stefson** [comment]
Yes, this line is from [1], so you consider it to be safe to adjust it?

**Comment by lluixhi** [comment]
Yeah.

**Comment by stefson** [comment]
You were most certainly right, [2] is a regression in gcc 6.x only - the corresponding test case was very helpfull. Thanks for the help! :)
