### ISSUE TITLE
mesa-12.0.2 ebuild file conflict with official musl overlay with nouveau

### ISSUE THREAD

**Issue by ennui93** [lluixhi/musl-extras#7]
Emerging the mesa-12.0.2 ebuild from the musl-extras overlay results in a file collision with `x11-libs/libva-vdpau-driver-0.7.4-r99::musl` at `/usr/lib/va/drivers/nouveau_drv_video.so`.

Possible fixes include:
- creating an `x11-libs/libva-vdpau-driver-0.7.4-r100` ebuild in the musl-extra overlay that doesn't apply `libva-vdpau-driver-0.7.4-nouveau.patch`
  - this is what I've done to workaround the problem in my own overlay
  - see https://gitweb.gentoo.org/user/ennui.git/commit/?h=musl&id=6f06f019aa8b98139a1d4d0f43ab3acb7154cd87
- pushing the mesa ebuild upstream to the official musl overlay and creating a new libva-vdpau-driver ebuild there to fix this issue

**Comment by lluixhi** [comment]
So what happened was upstream (::gentoo) added a new ebuild, x11-libs/libva-vdpau-driver-r4 which removed that patch for the reason you mentioned, but the musl overlay (::musl) had an ebuild with revision -r99 which was a modified version of x11-libs/libva-vdpau-driver-r3, so it was overridden.

They really need to stop doing that. 

Anyway, I added an x11-libs/libva-vdpau-driver ebuild to fix it. I need to get around to actually moving all this stuff upstream, but I have a lot of ebuilds to commit, and this sort of error is pretty frequent on their end, as far as I can tell -- so it'd be a lot of work.

**Comment by blueness** [comment]
@lluixhi "They really need to stop doing that." Sorry to steal an old bug report, but we can stop using -r99 now that we have more eyes watching the musl overlay.  It was originally a practice so I wouldn't break my automated stage3 builds on every rev bump in the tree.
